version: '3.8'
services:
  app:
    build: ./docker
    volumes:
      - ./config/ucenter_config.json:/usr/src/app/ucenter_config.json
    environment:
      - RABBITMQ_HOST=localhost
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
      - EXCHANGE_NAME=gnss_data_exchange
      - ROUTING_KEY=gnss_routing_key
      - PORT=/dev/ttyACM0
      - BAUDRATE=38400
      - TIMEOUT=1.0
      - UCENTER_JSON_FILE=/usr/src/app/ucenter_config.json
      - UBX_FILENAME=None
      - GNSS_MESSAGES=GNGGA,NAV-PVT
      - LOGGING_LEVEL=INFO
      - EXPERIMENT_ID=1
      - ALIAS=blake_test_rpi
      - PP_REGION=us
      - PP_PLAN=Lb
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
