version: '3.8'
services:
  app:
    build: ./docker
    volumes:
      - ./config/ucenter_config.json:/usr/src/app/ucenter_config.json
      - ./config/config.yaml:/usr/src/app/config.yaml
    environment:
      - CONFIG_FILE=/usr/src/app/config.yaml
      - RABBITMQ_HOST=192.168.1.100
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
      - EXCHANGE_NAME=gnss_data_exchange
      - ROUTING_KEY=gnss_routing_key
      - DEVICE_ID=blake_home_server
      - PORT=/dev/ttyUSB0
      - BAUDRATE=38400
      - TIMEOUT=1.0
      - UCENTER_JSON_FILE=/usr/src/app/ucenter_config.json
      - UBX_FILENAME=None
      - GNSS_MESSAGES=GNGGA
      - LOGGING_LEVEL=INFO
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
